Add support to signals and slots
mirko-bianco/FidoLib pull request #28
Opened 2021-11-28 20:36 UTC by mirko-bianco

2021-12-03 20:25 UTC, BasvRossem requested changes
Could you also create some tests for your slots?

2021-12-03 20:25 UTC, BasvRossem commented on source/Slots/Fido.Slots.pas
> +      function Slot: Spring.TAction<TArray<TValue>>;
Why not use a read only property? This seems a bit redundant...

2021-12-04 07:11 UTC, mirko-bianco commented
> Could you also create some tests for your slots?

I've been a sloth...

2021-12-05 19:30 UTC, mirko-bianco commented
> Could you also create some tests for your slots?


done

2021-12-12 18:49 UTC, BasvRossem approved these changes

2021-12-12 22:46 UTC, merged