Xmas2022
mirko-bianco/FidoLib pull request #64
Opened 2022-12-26 10:08 UTC by mirko-bianco

2022-12-29 20:00 UTC, BasvRossem requested changes

2022-12-30 15:48 UTC, silvioprog submitted a review, later dismissed

2023-01-03 18:24 UTC, BasvRossem approved these changes

2023-01-03 18:24 UTC, BasvRossem commented on source/Http/Fido.Http.Response.pas
>      Dictionary[Strings.Names[I]] := Strings.ValueFromIndex[I];
You could use the `StringsToDictionary` from Fido.Http.Utils here

2023-01-04 07:09 UTC, merged